/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tugas_trias.github.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("gists_url")
  private String gists_url = null;

  @JsonProperty("repos_url")
  private String repos_url = null;

  @JsonProperty("following_url")
  private String following_url = null;

  @JsonProperty("twitter_username")
  private String twitter_username = null;

  @JsonProperty("bio")
  private String bio = null;

  @JsonProperty("created_at")
  private String created_at = null;

  @JsonProperty("login")
  private String login = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("blog")
  private String blog = null;

  @JsonProperty("subscriptions_url")
  private String subscriptions_url = null;

  @JsonProperty("updated_at")
  private String updated_at = null;

  @JsonProperty("site_admin")
  private Boolean site_admin = null;

  @JsonProperty("company")
  private String company = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("public_repos")
  private Integer public_repos = null;

  @JsonProperty("gravatar_id")
  private String gravatar_id = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("organizations_url")
  private String organizations_url = null;

  @JsonProperty("hireable")
  private String hireable = null;

  @JsonProperty("starred_url")
  private String starred_url = null;

  @JsonProperty("followers_url")
  private String followers_url = null;

  @JsonProperty("public_gists")
  private Integer public_gists = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("received_events_url")
  private String received_events_url = null;

  @JsonProperty("followers")
  private Integer followers = null;

  @JsonProperty("avatar_url")
  private String avatar_url = null;

  @JsonProperty("events_url")
  private String events_url = null;

  @JsonProperty("html_url")
  private String html_url = null;

  @JsonProperty("following")
  private Integer following = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("location")
  private String location = null;

  @JsonProperty("node_id")
  private String node_id = null;

  public RootResponse gists_url(String gists_url) {
    this.gists_url = gists_url;
    return this;
  }

   /**
   * Get gists_url
   * @return gists_url
  **/
  public String getGistsUrl() {
    return gists_url;
  }

  public void setGistsUrl(String gists_url) {
    this.gists_url = gists_url;
  }

  public RootResponse repos_url(String repos_url) {
    this.repos_url = repos_url;
    return this;
  }

   /**
   * Get repos_url
   * @return repos_url
  **/
  public String getReposUrl() {
    return repos_url;
  }

  public void setReposUrl(String repos_url) {
    this.repos_url = repos_url;
  }

  public RootResponse following_url(String following_url) {
    this.following_url = following_url;
    return this;
  }

   /**
   * Get following_url
   * @return following_url
  **/
  public String getFollowingUrl() {
    return following_url;
  }

  public void setFollowingUrl(String following_url) {
    this.following_url = following_url;
  }

  public RootResponse twitter_username(String twitter_username) {
    this.twitter_username = twitter_username;
    return this;
  }

   /**
   * Get twitter_username
   * @return twitter_username
  **/
  public String getTwitterUsername() {
    return twitter_username;
  }

  public void setTwitterUsername(String twitter_username) {
    this.twitter_username = twitter_username;
  }

  public RootResponse bio(String bio) {
    this.bio = bio;
    return this;
  }

   /**
   * Get bio
   * @return bio
  **/
  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public RootResponse created_at(String created_at) {
    this.created_at = created_at;
    return this;
  }

   /**
   * Get created_at
   * @return created_at
  **/
  public String getCreatedAt() {
    return created_at;
  }

  public void setCreatedAt(String created_at) {
    this.created_at = created_at;
  }

  public RootResponse login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public RootResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RootResponse blog(String blog) {
    this.blog = blog;
    return this;
  }

   /**
   * Get blog
   * @return blog
  **/
  public String getBlog() {
    return blog;
  }

  public void setBlog(String blog) {
    this.blog = blog;
  }

  public RootResponse subscriptions_url(String subscriptions_url) {
    this.subscriptions_url = subscriptions_url;
    return this;
  }

   /**
   * Get subscriptions_url
   * @return subscriptions_url
  **/
  public String getSubscriptionsUrl() {
    return subscriptions_url;
  }

  public void setSubscriptionsUrl(String subscriptions_url) {
    this.subscriptions_url = subscriptions_url;
  }

  public RootResponse updated_at(String updated_at) {
    this.updated_at = updated_at;
    return this;
  }

   /**
   * Get updated_at
   * @return updated_at
  **/
  public String getUpdatedAt() {
    return updated_at;
  }

  public void setUpdatedAt(String updated_at) {
    this.updated_at = updated_at;
  }

  public RootResponse site_admin(Boolean site_admin) {
    this.site_admin = site_admin;
    return this;
  }

   /**
   * Get site_admin
   * @return site_admin
  **/
  public Boolean isSiteAdmin() {
    return site_admin;
  }

  public void setSiteAdmin(Boolean site_admin) {
    this.site_admin = site_admin;
  }

  public RootResponse company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public RootResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RootResponse public_repos(Integer public_repos) {
    this.public_repos = public_repos;
    return this;
  }

   /**
   * Get public_repos
   * @return public_repos
  **/
  public Integer getPublicRepos() {
    return public_repos;
  }

  public void setPublicRepos(Integer public_repos) {
    this.public_repos = public_repos;
  }

  public RootResponse gravatar_id(String gravatar_id) {
    this.gravatar_id = gravatar_id;
    return this;
  }

   /**
   * Get gravatar_id
   * @return gravatar_id
  **/
  public String getGravatarId() {
    return gravatar_id;
  }

  public void setGravatarId(String gravatar_id) {
    this.gravatar_id = gravatar_id;
  }

  public RootResponse email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public RootResponse organizations_url(String organizations_url) {
    this.organizations_url = organizations_url;
    return this;
  }

   /**
   * Get organizations_url
   * @return organizations_url
  **/
  public String getOrganizationsUrl() {
    return organizations_url;
  }

  public void setOrganizationsUrl(String organizations_url) {
    this.organizations_url = organizations_url;
  }

  public RootResponse hireable(String hireable) {
    this.hireable = hireable;
    return this;
  }

   /**
   * Get hireable
   * @return hireable
  **/
  public String getHireable() {
    return hireable;
  }

  public void setHireable(String hireable) {
    this.hireable = hireable;
  }

  public RootResponse starred_url(String starred_url) {
    this.starred_url = starred_url;
    return this;
  }

   /**
   * Get starred_url
   * @return starred_url
  **/
  public String getStarredUrl() {
    return starred_url;
  }

  public void setStarredUrl(String starred_url) {
    this.starred_url = starred_url;
  }

  public RootResponse followers_url(String followers_url) {
    this.followers_url = followers_url;
    return this;
  }

   /**
   * Get followers_url
   * @return followers_url
  **/
  public String getFollowersUrl() {
    return followers_url;
  }

  public void setFollowersUrl(String followers_url) {
    this.followers_url = followers_url;
  }

  public RootResponse public_gists(Integer public_gists) {
    this.public_gists = public_gists;
    return this;
  }

   /**
   * Get public_gists
   * @return public_gists
  **/
  public Integer getPublicGists() {
    return public_gists;
  }

  public void setPublicGists(Integer public_gists) {
    this.public_gists = public_gists;
  }

  public RootResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public RootResponse received_events_url(String received_events_url) {
    this.received_events_url = received_events_url;
    return this;
  }

   /**
   * Get received_events_url
   * @return received_events_url
  **/
  public String getReceivedEventsUrl() {
    return received_events_url;
  }

  public void setReceivedEventsUrl(String received_events_url) {
    this.received_events_url = received_events_url;
  }

  public RootResponse followers(Integer followers) {
    this.followers = followers;
    return this;
  }

   /**
   * Get followers
   * @return followers
  **/
  public Integer getFollowers() {
    return followers;
  }

  public void setFollowers(Integer followers) {
    this.followers = followers;
  }

  public RootResponse avatar_url(String avatar_url) {
    this.avatar_url = avatar_url;
    return this;
  }

   /**
   * Get avatar_url
   * @return avatar_url
  **/
  public String getAvatarUrl() {
    return avatar_url;
  }

  public void setAvatarUrl(String avatar_url) {
    this.avatar_url = avatar_url;
  }

  public RootResponse events_url(String events_url) {
    this.events_url = events_url;
    return this;
  }

   /**
   * Get events_url
   * @return events_url
  **/
  public String getEventsUrl() {
    return events_url;
  }

  public void setEventsUrl(String events_url) {
    this.events_url = events_url;
  }

  public RootResponse html_url(String html_url) {
    this.html_url = html_url;
    return this;
  }

   /**
   * Get html_url
   * @return html_url
  **/
  public String getHtmlUrl() {
    return html_url;
  }

  public void setHtmlUrl(String html_url) {
    this.html_url = html_url;
  }

  public RootResponse following(Integer following) {
    this.following = following;
    return this;
  }

   /**
   * Get following
   * @return following
  **/
  public Integer getFollowing() {
    return following;
  }

  public void setFollowing(Integer following) {
    this.following = following;
  }

  public RootResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RootResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public RootResponse node_id(String node_id) {
    this.node_id = node_id;
    return this;
  }

   /**
   * Get node_id
   * @return node_id
  **/
  public String getNodeId() {
    return node_id;
  }

  public void setNodeId(String node_id) {
    this.node_id = node_id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.gists_url, RootResponse.gists_url) &&
        Objects.equals(this.repos_url, RootResponse.repos_url) &&
        Objects.equals(this.following_url, RootResponse.following_url) &&
        Objects.equals(this.twitter_username, RootResponse.twitter_username) &&
        Objects.equals(this.bio, RootResponse.bio) &&
        Objects.equals(this.created_at, RootResponse.created_at) &&
        Objects.equals(this.login, RootResponse.login) &&
        Objects.equals(this.type, RootResponse.type) &&
        Objects.equals(this.blog, RootResponse.blog) &&
        Objects.equals(this.subscriptions_url, RootResponse.subscriptions_url) &&
        Objects.equals(this.updated_at, RootResponse.updated_at) &&
        Objects.equals(this.site_admin, RootResponse.site_admin) &&
        Objects.equals(this.company, RootResponse.company) &&
        Objects.equals(this.id, RootResponse.id) &&
        Objects.equals(this.public_repos, RootResponse.public_repos) &&
        Objects.equals(this.gravatar_id, RootResponse.gravatar_id) &&
        Objects.equals(this.email, RootResponse.email) &&
        Objects.equals(this.organizations_url, RootResponse.organizations_url) &&
        Objects.equals(this.hireable, RootResponse.hireable) &&
        Objects.equals(this.starred_url, RootResponse.starred_url) &&
        Objects.equals(this.followers_url, RootResponse.followers_url) &&
        Objects.equals(this.public_gists, RootResponse.public_gists) &&
        Objects.equals(this.url, RootResponse.url) &&
        Objects.equals(this.received_events_url, RootResponse.received_events_url) &&
        Objects.equals(this.followers, RootResponse.followers) &&
        Objects.equals(this.avatar_url, RootResponse.avatar_url) &&
        Objects.equals(this.events_url, RootResponse.events_url) &&
        Objects.equals(this.html_url, RootResponse.html_url) &&
        Objects.equals(this.following, RootResponse.following) &&
        Objects.equals(this.name, RootResponse.name) &&
        Objects.equals(this.location, RootResponse.location) &&
        Objects.equals(this.node_id, RootResponse.node_id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gists_url, repos_url, following_url, twitter_username, bio, created_at, login, type, blog, subscriptions_url, updated_at, site_admin, company, id, public_repos, gravatar_id, email, organizations_url, hireable, starred_url, followers_url, public_gists, url, received_events_url, followers, avatar_url, events_url, html_url, following, name, location, node_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    gists_url: ").append(toIndentedString(gists_url)).append("\n");
    sb.append("    repos_url: ").append(toIndentedString(repos_url)).append("\n");
    sb.append("    following_url: ").append(toIndentedString(following_url)).append("\n");
    sb.append("    twitter_username: ").append(toIndentedString(twitter_username)).append("\n");
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("    created_at: ").append(toIndentedString(created_at)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    blog: ").append(toIndentedString(blog)).append("\n");
    sb.append("    subscriptions_url: ").append(toIndentedString(subscriptions_url)).append("\n");
    sb.append("    updated_at: ").append(toIndentedString(updated_at)).append("\n");
    sb.append("    site_admin: ").append(toIndentedString(site_admin)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    public_repos: ").append(toIndentedString(public_repos)).append("\n");
    sb.append("    gravatar_id: ").append(toIndentedString(gravatar_id)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    organizations_url: ").append(toIndentedString(organizations_url)).append("\n");
    sb.append("    hireable: ").append(toIndentedString(hireable)).append("\n");
    sb.append("    starred_url: ").append(toIndentedString(starred_url)).append("\n");
    sb.append("    followers_url: ").append(toIndentedString(followers_url)).append("\n");
    sb.append("    public_gists: ").append(toIndentedString(public_gists)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    received_events_url: ").append(toIndentedString(received_events_url)).append("\n");
    sb.append("    followers: ").append(toIndentedString(followers)).append("\n");
    sb.append("    avatar_url: ").append(toIndentedString(avatar_url)).append("\n");
    sb.append("    events_url: ").append(toIndentedString(events_url)).append("\n");
    sb.append("    html_url: ").append(toIndentedString(html_url)).append("\n");
    sb.append("    following: ").append(toIndentedString(following)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    node_id: ").append(toIndentedString(node_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
